Repository boostcampwm-2024/iOS04-PhotoGether, pull requests merged in 2024-12, with the labels that each got.

#142 [FEAT/#132] 드래그 제스처 구현
  PhotoGether/DataLayer/PhotoGetherData/PhotoGetherData/EventHub/EventHub.swift
  PhotoGether/DataLayer/PhotoGetherData/PhotoGetherData/ServiceImpl/SignalingServiceImpl.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/CanvasScrollView.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/EditPhotoRoomGuestViewController.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/EditPhotoRoomGuestViewModel.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/EditPhotoRoomHostViewController.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/EditPhotoRoomHostViewModel.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/View/StickerView.swift
Labels: ✨ feat

#147 [FIX/#144] StickerView 터치 영역 개선
  PhotoGether/PresentationLayer/DesignSystem/DesignSystem/Resource/DesignSystem.xcassets/PTGIcon/PTGresize.imageset/Contents.json
  PhotoGether/PresentationLayer/DesignSystem/DesignSystem/Resource/DesignSystem.xcassets/PTGIcon/PTGresize.imageset/PTGresize.svg
  PhotoGether/PresentationLayer/DesignSystem/DesignSystem/Source/PTGImage.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/CanvasScrollView.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/View/StickerView.swift
Labels: ✨ feat, 🔧 fix

#138 [HOTFIX/#137] 다인 연결이 안되던 문제를 수정합니다.
  PhotoGether/DataLayer/PhotoGetherData/PhotoGetherData/ConnectionClientImpl.swift
  PhotoGether/DataLayer/PhotoGetherData/PhotoGetherData/ConnectionRepositoryImpl.swift
  PhotoGether/DataLayer/PhotoGetherData/PhotoGetherData/Interface/Message/IceCandidateMessage.swift
  PhotoGether/DataLayer/PhotoGetherData/PhotoGetherData/Interface/Message/SessionDescriptionMessage.swift
  PhotoGether/DataLayer/PhotoGetherData/PhotoGetherData/Interface/Service/SignalingService.swift
  PhotoGether/DataLayer/PhotoGetherData/PhotoGetherData/Interface/Service/WebRTCService.swift
  PhotoGether/DataLayer/PhotoGetherData/PhotoGetherData/ServiceImpl/SignalingServiceImpl.swift
  PhotoGether/DataLayer/PhotoGetherData/PhotoGetherData/ServiceImpl/WebRTCServiceImpl.swift
  PhotoGether/DomainLayer/PhotoGetherDomain/PhotoGetherDomain/UseCaseImpl/SendOfferUseCaseImpl.swift
  PhotoGether/DomainLayer/PhotoGetherDomain/PhotoGetherDomainInterface/ConnectionClient.swift
  PhotoGether/DomainLayer/PhotoGetherDomain/PhotoGetherDomainInterface/Repository/ConnectionRepository.swift
  PhotoGether/DomainLayer/PhotoGetherDomain/PhotoGetherDomainInterface/UseCase/SendOfferUseCase.swift
  PhotoGether/PhotoGether/App/SceneDelegate.swift
  PhotoGether/PresentationLayer/WaitingRoomFeature/WaitingRoomFeature/Source/View/WaitingRoomView.swift
  PhotoGether/PresentationLayer/WaitingRoomFeature/WaitingRoomFeature/Source/ViewController/WaitingRoomViewController.swift
  PhotoGether/PresentationLayer/WaitingRoomFeature/WaitingRoomFeature/Source/ViewModel/WaitingRoomViewModel.swift
  PhotoGetherServer/PhotoGetherServer/Sources/App/DTO/Message/IceCandidateMessage.swift
  PhotoGetherServer/PhotoGetherServer/Sources/App/Model/RoomManager.swift
  PhotoGetherServer/PhotoGetherServer/Sources/App/Utils/WebSocket+decodeDTO.swift
  PhotoGetherServer/PhotoGetherServer/Sources/App/Utils/WebSocket+sendDTO.swift
Labels: 🔧 fix

#149 [FIX/#146] 캡쳐 로직 수정 및 최적화
  PhotoGether/DataLayer/PhotoGetherData/PhotoGetherData/CapturableVideoView.swift
Labels: 🔧 fix, ⚙️ refactor

#152 [FEAT/#148] 스티커 사이즈 조절 기능 추가
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/CanvasScrollView.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/EditPhotoRoomGuestViewController.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/EditPhotoRoomGuestViewModel.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/EditPhotoRoomHostViewController.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/EditPhotoRoomHostViewModel.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/View/StickerView.swift
Labels: ✨ feat

#150 [HOTFIX/#145] 다인 연결이 안되는 문제를 해결합니다.
  PhotoGether/DataLayer/PhotoGetherData/PhotoGetherData/ConnectionClientImpl.swift
  PhotoGether/DataLayer/PhotoGetherData/PhotoGetherData/ConnectionRepositoryImpl.swift
  PhotoGether/DataLayer/PhotoGetherData/PhotoGetherData/Extension/UIView+flipHorizontally.swift
  PhotoGether/DataLayer/PhotoGetherData/PhotoGetherData/Interface/Service/WebRTCService.swift
  PhotoGether/DataLayer/PhotoGetherData/PhotoGetherData/PeerConnectionSupport.swift
  PhotoGether/DataLayer/PhotoGetherData/PhotoGetherData/ServiceImpl/WebRTCServiceImpl.swift
  PhotoGether/DomainLayer/PhotoGetherDomain/PhotoGetherDomainInterface/ConnectionClient.swift
Labels: 🔧 fix

#160 [FEAT/#143] 몬생긴 이모지를 교체했습니다
  PhotoGether/DataLayer/PhotoGetherData/PhotoGetherData/EmojiDTO.swift
  PhotoGether/DataLayer/PhotoGetherData/PhotoGetherData/ShapeRepositoryImpl.swift
  PhotoGether/DomainLayer/PhotoGetherDomain/PhotoGetherDomain/UseCaseImpl/FetchEmojiListUseCaseImpl.swift
  PhotoGether/DomainLayer/PhotoGetherDomain/PhotoGetherDomainInterface/Entity/EmojiEntity.swift
  PhotoGether/DomainLayer/PhotoGetherDomain/PhotoGetherDomainInterface/Repository/ShapeRepository.swift
  PhotoGether/DomainLayer/PhotoGetherDomain/PhotoGetherDomainInterface/UseCase/FetchEmojiListUseCase.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/EditPhotoRoomGuestViewController.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/EditPhotoRoomHostViewController.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/StickerBottomSheetViewController.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/StickerBottomSheetViewModel.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/StickerCollectionViewCell.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/View/StickerView.swift
Labels: ⚙️ refactor

#159 [FEAT/#157] 사진 촬영 완료 후 EditPhoto 화면으로 이동 시 비디오 캡쳐를 중단합니다.
  PhotoGether/Core/CoreModule/CoreModule.xcodeproj/project.pbxproj
  PhotoGether/DataLayer/PhotoGetherData/PhotoGetherData.xcodeproj/project.pbxproj
  PhotoGether/DataLayer/PhotoGetherData/PhotoGetherData/ConnectionRepositoryImpl.swift
  PhotoGether/DataLayer/PhotoGetherNetwork/PhotoGetherNetwork.xcodeproj/project.pbxproj
  PhotoGether/DomainLayer/PhotoGetherDomain/PhotoGetherDomain.xcodeproj/project.pbxproj
  PhotoGether/DomainLayer/PhotoGetherDomain/PhotoGetherDomain/UseCaseImpl/StopVideoCaptureUseCaseImpl.swift
  PhotoGether/DomainLayer/PhotoGetherDomain/PhotoGetherDomainInterface/Repository/ConnectionRepository.swift
  PhotoGether/DomainLayer/PhotoGetherDomain/PhotoGetherDomainInterface/UseCase/StopVideoCaptureUseCase.swift
  PhotoGether/PhotoGether/App/SceneDelegate.swift
  PhotoGether/PresentationLayer/BaseFeature/BaseFeature.xcodeproj/project.pbxproj
  PhotoGether/PresentationLayer/DesignSystem/DesignSystem.xcodeproj/project.pbxproj
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature.xcodeproj/project.pbxproj
  PhotoGether/PresentationLayer/PhotoRoomFeature/PhotoRoomFeature.xcodeproj/project.pbxproj
  PhotoGether/PresentationLayer/PhotoRoomFeature/PhotoRoomFeature/Source/ViewModel/PhotoRoomViewModel.swift
  PhotoGether/PresentationLayer/SharePhotoFeature/SharePhotoFeature.xcodeproj/project.pbxproj
  PhotoGether/PresentationLayer/WaitingRoomFeature/WaitingRoomFeature.xcodeproj/project.pbxproj
Labels: ✨ feat

#169 [FIX/#164] 스티커 동시 터치 방지
  PhotoGether/PresentationLayer/DesignSystem/DesignSystem/Source/PTGGrayButton.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/EditPhotoHostBottomView.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/View/StickerView.swift
Labels: 🔧 fix

#171 [ FIX/#166] 편집 화면에서 다음 화면으로 전환될 때 바텀시트를 내려줍니다.
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/EditPhotoRoomGuestViewController.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/EditPhotoRoomHostViewController.swift
Labels: 🔧 fix

#172 [FIX/#170] 편집화면에서 호스트가 다음화면으로 이동 시 노티피케이션을 두 번 보내는 문제를 해결
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/EditPhotoRoomHostViewController.swift
Labels: 🔧 fix

#178 [ FEAT/#176] 유저 컬러를 추가해줬습니다
  PhotoGether/DomainLayer/PhotoGetherDomain/PhotoGetherDomainInterface/Entity/UserInfo.swift
  PhotoGether/PresentationLayer/DesignSystem/DesignSystem/Source/UIColor+.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/View/StickerView.swift
Labels: ✨ feat

#180 [FIX/#175] 데모를 위한 일부 기능 오류 수정
  PhotoGether/DomainLayer/PhotoGetherDomain/PhotoGetherDomain/UseCaseImpl/CaptureVideosUseCaseImpl.swift
  PhotoGether/DomainLayer/PhotoGetherDomain/PhotoGetherDomainInterface/Entity/UserInfo.swift
  PhotoGether/PresentationLayer/DesignSystem/DesignSystem/Source/UIColor+.swift
  PhotoGether/PresentationLayer/EditPhotoRoomFeature/EditPhotoRoomFeature/Source/View/StickerView.swift
  PhotoGether/PresentationLayer/PhotoRoomFeature/PhotoRoomFeature/Source/View/PhotoRoomBottomView.swift
  PhotoGether/PresentationLayer/PhotoRoomFeature/PhotoRoomFeature/Source/ViewController/PhotoRoomViewController.swift
  PhotoGether/PresentationLayer/WaitingRoomFeature/WaitingRoomFeature/Source/View/WaitingRoomView.swift
  PhotoGether/PresentationLayer/WaitingRoomFeature/WaitingRoomFeature/Source/ViewController/WaitingRoomViewController.swift
  PhotoGether/PresentationLayer/WaitingRoomFeature/WaitingRoomFeature/Source/ViewModel/WaitingRoomViewModel.swift
Labels: ✨ feat, 🔧 fix
